(function(){"use strict";
var fields=[
 {key:"paddingLeft",name:"左边距",icon:"padding-left",group:"padding"},
 {key:"paddingRight",name:"右边距",icon:"padding-right",group:"padding"},
 {key:"paddingTop",name:"上边距",icon:"padding-top",group:"padding"},
 {key:"paddingBottom",name:"下边距",icon:"padding-bottom",group:"padding"},
 {key:"column",name:"列数",icon:"column",group:"count",integer:true},
 {key:"row",name:"行数",icon:"row",group:"count",integer:true},
 {key:"columnWidth",name:"列宽度",icon:"column-width",group:"size"},
 {key:"rowHeight",name:"行高度",icon:"row-height",group:"size"},
 {key:"columnSpace",name:"列间距",icon:"column-space",group:"gap"},
 {key:"rowSpace",name:"行间距",icon:"row-space",group:"gap"},
 {key:"colCenter",name:"垂直居中",icon:"column-center",group:"center"},
 {key:"rowCenter",name:"水平居中",icon:"row-center",group:"center"}
];
var patterns=[
 {fn:"golden1",name:"黄金矩形",icon:1}, {fn:"golden2",name:"黄金矩形",icon:2},
 {fn:"golden3",name:"黄金矩形",icon:3,vertical:true}, {fn:"golden4",name:"黄金矩形",icon:4,vertical:true},
 {fn:"golden5",name:"螺旋线",icon:5}, {fn:"golden6",name:"螺旋线",icon:6,vertical:true},
 {fn:"golden7",name:"黄金分割",icon:7}, {fn:"golden8",name:"黄金分割",icon:8,vertical:true},
 {fn:"golden9",name:"十字格",icon:9}, {fn:"golden10",name:"九宫格",icon:10},
 {fn:"golden11",name:"黄金比例",icon:11}, {fn:"golden12",name:"交叉线",icon:12},
 {fn:"golden13",name:"V字行",icon:13}, {fn:"golden14",name:"V字行",icon:14,vertical:true},
 {fn:"golden15",name:"对角线",icon:15}, {fn:"golden16",name:"对角线",icon:16},
 {fn:"golden17",name:"黄金切割",icon:17}, {fn:"golden18",name:"黄金切割",icon:18,vertical:true},
 {fn:"golden19",name:"三分切割",icon:19}, {fn:"golden20",name:"三分切割",icon:20,vertical:true},
 {fn:"golden21",name:"垂直切割",icon:21}
];
var fieldNodes={},toastTimer=0,storageKey="xinyang.guide.presets.v3",activeGroup="";
function svgUse(name){return '<svg aria-hidden="true"><use href="#i-'+name+'"></use></svg>'}
function parentRuntime(){try{return window.parent&&window.parent.XinyangRuntime}catch(e){return null}}
function host(method,payload){var runtime=parentRuntime();if(!runtime||typeof runtime.hostInvoke!=="function")return Promise.reject(new Error("参考线宿主接口未加载"));return runtime.hostInvoke(method,payload||{});}
function parentStatus(message){try{if(window.parent.XinyangStatus&&window.parent.XinyangStatus.set)window.parent.XinyangStatus.set(message)}catch(e){}}
function toast(message){var node=document.getElementById("toast");node.textContent=message;node.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(function(){node.classList.remove("show")},1600);parentStatus(message)}
function errorText(error){return error&&error.message?error.message:String(error||"操作失败")}
function sourceName(source){return source==="selection"?"当前选区":source==="selected-layers"?"多个选中图层":source==="layer"?"当前图层":"画布"}
function normalizeMeasure(value){var text=String(value||"").trim().replace(/，/g,".");if(!text)return "";if(/^[-+]?\d+(?:\.\d+)?(?:px|%|cm|mm|in|pt|pc)?$/i.test(text))return text;var match=text.match(/[-+]?\d+(?:\.\d+)?/);if(!match)return "";var unit=(text.match(/px|%|cm|mm|in|pt|pc/i)||[""])[0];return match[0]+unit}
function values(){var output={isLayer:document.getElementById("use-layer").checked};fields.forEach(function(field){output[field.key]=(fieldNodes[field.key].value||"").trim()});return output}
function hasValue(){var ready=fields.some(function(field){return (fieldNodes[field.key].value||"").trim()!==""});document.getElementById("create-guides").classList.toggle("ready",ready);document.getElementById("save-preset").classList.toggle("ready",ready);document.getElementById("reset-form").classList.toggle("ready",ready);return ready}
function setGroupHover(group,on){if(on)activeGroup=group;else if(activeGroup===group)activeGroup="";document.querySelectorAll(".field").forEach(function(node){node.classList.toggle("group-hover",!!activeGroup&&node.dataset.group===activeGroup)})}
function renderFields(){var root=document.getElementById("field-grid");fields.forEach(function(field){var wrap=document.createElement("label");wrap.className="field";wrap.dataset.group=field.group;wrap.innerHTML='<span class="field-icon">'+svgUse(field.icon)+'</span><input autocomplete="off" spellcheck="false" placeholder="'+field.name+'"><span class="field-right"><button type="button" class="assign" title="同步同组参数">'+svgUse("assign")+'</button></span>';var input=wrap.querySelector("input"),assign=wrap.querySelector("button");fieldNodes[field.key]=input;wrap.addEventListener("mouseenter",function(){setGroupHover(field.group,true)});wrap.addEventListener("mouseleave",function(){setTimeout(function(){if(!wrap.matches(":hover"))setGroupHover(field.group,false)},260)});input.addEventListener("focus",function(){wrap.classList.add("active")});input.addEventListener("blur",function(){wrap.classList.remove("active");input.value=field.integer?input.value.replace(/[^\d]/g,""):normalizeMeasure(input.value);hasValue()});input.addEventListener("input",function(){if(field.integer)input.value=input.value.replace(/[^\d]/g,"");hasValue()});input.addEventListener("keydown",function(event){if(event.key==="Enter")createGuides(event)});assign.addEventListener("click",function(event){event.preventDefault();event.stopPropagation();var value=input.value;fields.filter(function(item){return item.group===field.group}).forEach(function(item){fieldNodes[item.key].value=value});hasValue()});root.appendChild(wrap)})}
function refreshContext(){var useLayer=document.getElementById("use-layer").checked;host("guide.context",{isLayer:useLayer}).then(function(result){var label=document.getElementById("target-label");label.classList.toggle("active",useLayer);if(!result.hasDocument){label.title="请先打开 Photoshop 文档";return}label.title="当前范围："+sourceName(result.source)+" · "+Math.round(result.bounds.width)+" × "+Math.round(result.bounds.height)+" px；快捷按钮优先选区，其次选中图层，最后画布";parentStatus("参考线范围："+sourceName(result.source))}).catch(function(error){document.getElementById("target-label").title=errorText(error)})}
function createGuides(event){if(!hasValue())return toast("请至少填写一个参数");var payload=values();if(event&&event.ctrlKey)payload.isLayer=false;if(event&&event.shiftKey)payload.isLayer=true;host("guide.create",payload).then(function(result){toast("已按"+sourceName(result.source)+"创建 "+result.added+" 条参考线");refreshContext()}).catch(function(error){toast(errorText(error))})}
function quickGuide(type,event){
 var runtime=parentRuntime();
 var forceCanvas=!!(event&&(event.ctrlKey||event.metaKey));
 if(!runtime||typeof runtime.evalScriptRaw!=="function"){toast("参考线宿主接口未加载");return}
 var typeText=String(type||"");
 var script='(function(){var oldUnits=null;try{'+
 'if(!app.documents.length)return "__ERROR__请先打开 Photoshop 文档";'+
 'var d=app.activeDocument;oldUnits=app.preferences.rulerUnits;app.preferences.rulerUnits=Units.PIXELS;'+
 'function px(v){try{return Number(v.as("px"));}catch(e){return Number(v)||0;}}'+
 'function ids(){var a=[];try{var k=stringIDToTypeID("targetLayersIDs"),r=new ActionReference();r.putProperty(stringIDToTypeID("property"),k);r.putEnumerated(stringIDToTypeID("document"),stringIDToTypeID("ordinal"),stringIDToTypeID("targetEnum"));var q=executeActionGet(r);if(q.hasKey(k)){var l=q.getList(k);for(var i=0;i<l.count;i++)a.push(l.getReference(i).getIdentifier(charIDToTypeID("Lyr ")));}}catch(e){}if(!a.length){try{var p=charIDToTypeID("LyrI"),rr=new ActionReference();rr.putProperty(charIDToTypeID("Prpr"),p);rr.putEnumerated(charIDToTypeID("Lyr "),charIDToTypeID("Ordn"),charIDToTypeID("Trgt"));a.push(executeActionGet(rr).getInteger(p));}catch(e2){}}return a;}'+
 'function unionLayers(){var wanted={},arr=ids(),out=null;for(var i=0;i<arr.length;i++)wanted["i"+arr[i]]=1;function walk(c){for(var j=0;j<c.layers.length;j++){var L=c.layers[j],id=-1;try{id=Number(L.id);}catch(e){}if(wanted["i"+id]){try{var b=L.bounds,l=px(b[0]),t=px(b[1]),r=px(b[2]),bt=px(b[3]);if(r>l&&bt>t){if(!out)out={left:l,top:t,right:r,bottom:bt};else{out.left=Math.min(out.left,l);out.top=Math.min(out.top,t);out.right=Math.max(out.right,r);out.bottom=Math.max(out.bottom,bt);}}}catch(e2){}}if(L.typename==="LayerSet")walk(L);}}walk(d);return out;}'+
 'var b=null,source="canvas";if(!'+(forceCanvas?'true':'false')+'){try{var s=d.selection.bounds,sl=px(s[0]),st=px(s[1]),sr=px(s[2]),sb=px(s[3]);if(sr>sl&&sb>st){b={left:sl,top:st,right:sr,bottom:sb};source="selection";}}catch(es){}if(!b){b=unionLayers();if(b)source="layer";}}if(!b)b={left:0,top:0,right:px(d.width),bottom:px(d.height)};b.width=b.right-b.left;b.height=b.bottom-b.top;'+
 'var type='+JSON.stringify(typeText)+',dir=null,pos=0;if(type==="guide-left"){dir=Direction.VERTICAL;pos=b.left;}else if(type==="guide-right"){dir=Direction.VERTICAL;pos=b.right;}else if(type==="guide-top"){dir=Direction.HORIZONTAL;pos=b.top;}else if(type==="guide-bottom"){dir=Direction.HORIZONTAL;pos=b.bottom;}else if(type==="guide-center"){dir=Direction.VERTICAL;pos=b.left+b.width/2;}else if(type==="guide-middle"){dir=Direction.HORIZONTAL;pos=b.top+b.height/2;}else return "__ERROR__未知快捷参考线类型";'+
 'var exists=false;for(var g=0;g<d.guides.length;g++){try{var it=d.guides[g],same=(it.direction===dir),gp=px(it.coordinate);if(same&&Math.abs(gp-pos)<0.5){exists=true;break;}}catch(eg){}}if(!exists)d.guides.add(dir,UnitValue(pos,"px"));return "__OK__|"+(exists?0:1)+"|"+source;'+
 '}catch(e){return "__ERROR__"+String(e&&e.message?e.message:e);}finally{try{if(oldUnits!==null)app.preferences.rulerUnits=oldUnits;}catch(ee){}}})()';
 runtime.evalScriptRaw(script,{label:"guideQuickNative",slowAfterMs:3000}).then(function(raw){raw=String(raw||"");if(raw.indexOf("__ERROR__")===0)throw new Error(raw.slice(9));var parts=raw.split("|");var added=Number(parts[1])||0;var source=parts[2]||"canvas";toast((added?"已创建":"参考线已存在")+" · "+sourceName(source))}).catch(function(error){toast(errorText(error))})
}
function clearGuides(event){host("guide.clear",{clearRowGuides:!!(event&&(event.ctrlKey||event.metaKey)),clearColGuides:!!(event&&event.shiftKey)}).then(function(result){toast("已清除 "+result.removed+" 条参考线")}).catch(function(error){toast(errorText(error))})}
function readPresets(){try{var data=JSON.parse(localStorage.getItem(storageKey)||"[]");return Array.isArray(data)?data:[]}catch(e){return[]}}
function writePresets(data){try{localStorage.setItem(storageKey,JSON.stringify(data))}catch(e){}}
function presetDetails(info){var output=[];fields.forEach(function(field){var value=info&&info[field.key];if(value!==undefined&&value!==null&&String(value)!=="")output.push('<div class="preset-info"><span>'+field.name+'</span> '+String(value).replace(/[<>]/g,"")+'</div>')});return output.join("")}
function renderPresets(){var list=document.getElementById("preset-list"),data=readPresets();list.innerHTML="";if(!data.length){list.innerHTML='<p class="empty">没有找到预设</p>';return}data.forEach(function(item,index){var row=document.createElement("div");row.className="preset-item";row.innerHTML='<div class="preset-base"><div class="preset-name"></div><button class="preset-fn info" title="查看参数">i</button><button class="preset-fn delete" title="删除">×</button></div><div class="preset-details">'+presetDetails(item.info||{})+'</div>';row.querySelector(".preset-name").textContent=item.name||"未命名方案";row.querySelector(".preset-base").addEventListener("click",function(event){if(event.target.closest("button"))return;Object.keys(item.info||{}).forEach(function(key){if(fieldNodes[key])fieldNodes[key].value=item.info[key]||""});hasValue();togglePreset(false);createGuides()});row.querySelector(".info").onclick=function(event){event.stopPropagation();row.classList.toggle("details-open")};row.querySelector(".delete").onclick=function(event){event.stopPropagation();if(confirm("删除后将不可恢复，是否删除？")){data.splice(index,1);writePresets(data);renderPresets()}};list.appendChild(row)})}
function savePreset(){if(!hasValue())return toast("没有可保存的参数");var name=prompt("请输入名称","未命名方案");if(name===null)return;name=(name||"未命名方案").trim();var info=values();delete info.isLayer;var data=readPresets();data.push({name:name,info:info});writePresets(data);renderPresets();toast("预设已保存")}
function resetForm(){fields.forEach(function(field){fieldNodes[field.key].value=""});hasValue()}
function togglePreset(open){var panel=document.getElementById("preset-panel"),form=document.getElementById("reference-form"),button=document.getElementById("toggle-presets");panel.hidden=!open;form.hidden=open;button.classList.toggle("open",open);if(open)renderPresets()}
function patternSvg(index,vertical){var w=vertical?25:49,h=35,phi1=Math.round(w*.382),phi2=Math.round(w*.618),y1=Math.round(h*.382),y2=Math.round(h*.618),path="";switch(index){case 1:path='M.5.5h'+(w-1)+'v'+(h-1)+'H.5zM'+phi2+' .5v'+(h-1)+'M.5 '+y2+'h'+phi2;break;case 2:path='M.5.5h'+(w-1)+'v'+(h-1)+'H.5zM'+phi1+' .5v'+(h-1);break;case 3:path='M.5.5h'+(w-1)+'v'+(h-1)+'H.5zM.5 '+y1+'h'+(w-1)+'M'+phi1+' .5v'+y1;break;case 4:path='M.5.5h'+(w-1)+'v'+(h-1)+'H.5zM.5 '+y2+'h'+(w-1)+'M'+phi2+' '+y2+'v'+(h-y2-1);break;case 5:path='M1 '+(h-1)+'C4 8 '+Math.round(w*.55)+' 2 '+(w-2)+' '+Math.round(h*.55)+'C'+(w-5)+' '+(h-4)+' '+Math.round(w*.62)+' '+(h-3)+' '+Math.round(w*.58)+' '+Math.round(h*.68);break;case 6:path='M1 1C4 '+(h-8)+' '+Math.round(w*.55)+' '+(h-2)+' '+(w-2)+' '+Math.round(h*.45)+'C'+(w-5)+' 4 '+Math.round(w*.62)+' 3 '+Math.round(w*.58)+' '+Math.round(h*.32);break;case 7:path='M'+phi1+' 0v'+h+'M'+phi2+' 0v'+h;break;case 8:path='M0 '+y1+'h'+w+'M0 '+y2+'h'+w;break;case 9:path='M'+Math.round(w/2)+' 0v'+h+'M0 '+Math.round(h/2)+'h'+w;break;case 10:path='M'+Math.round(w/3)+' 0v'+h+'M'+Math.round(w*2/3)+' 0v'+h+'M0 '+Math.round(h/3)+'h'+w+'M0 '+Math.round(h*2/3)+'h'+w;break;case 11:path='M'+phi1+' 0v'+h+'M'+phi2+' 0v'+h+'M0 '+y1+'h'+w+'M0 '+y2+'h'+w;break;case 12:path='M0 0l'+w+' '+h+'M0 '+h+'L'+w+' 0';break;case 13:path='M0 0l'+Math.round(w/2)+' '+h+'L'+w+' 0';break;case 14:path='M0 '+h+'L'+Math.round(w/2)+' 0l'+Math.round(w/2)+' '+h;break;case 15:path='M0 0l'+w+' '+h;break;case 16:path='M0 '+h+'L'+w+' 0';break;case 17:path='M'+phi1+' 0v'+h+'M0 '+y2+'h'+w+'M0 0l'+w+' '+h;break;case 18:path='M0 '+y1+'h'+w+'M'+phi2+' 0v'+h+'M0 '+h+'L'+w+' 0';break;case 19:path='M'+Math.round(w/3)+' 0v'+h+'M'+Math.round(w*2/3)+' 0v'+h;break;case 20:path='M0 '+Math.round(h/3)+'h'+w+'M0 '+Math.round(h*2/3)+'h'+w;break;default:path='M'+Math.round(w/2)+' 0v'+h}return '<svg viewBox="0 0 '+w+' '+h+'"><path d="'+path+'"/></svg>'}
function renderPatterns(){var root=document.getElementById("composition-grid");patterns.forEach(function(pattern){var button=document.createElement("button");button.className="composition-card"+(pattern.vertical?" vertical":"");button.type="button";button.innerHTML='<div class="icon">'+patternSvg(pattern.icon,pattern.vertical)+'</div><p>'+pattern.name+'</p>';button.onclick=function(){host("guide.composition",{fn:pattern.fn}).then(function(result){toast("已创建"+result.pattern+"，共 "+result.created+" 条构图线")}).catch(function(error){toast(errorText(error))})};root.appendChild(button)})}
function bind(){document.querySelectorAll(".tab").forEach(function(tab){tab.onclick=function(){document.querySelectorAll(".tab").forEach(function(node){node.classList.remove("active")});document.querySelectorAll(".tab-panel").forEach(function(node){node.classList.remove("active")});tab.classList.add("active");document.getElementById(tab.dataset.tab+"-panel").classList.add("active")}});document.getElementById("use-layer").onchange=refreshContext;document.getElementById("create-guides").onclick=createGuides;document.getElementById("save-preset").onclick=savePreset;document.getElementById("reset-form").onclick=resetForm;document.querySelectorAll("[data-quick]").forEach(function(button){button.onclick=function(event){quickGuide(button.dataset.quick,event)}});document.getElementById("clear-guides").onclick=clearGuides;document.getElementById("toggle-presets").onclick=function(){togglePreset(document.getElementById("preset-panel").hidden)};document.querySelectorAll("[data-perspective]").forEach(function(button){button.onclick=function(){host("guide.perspective",{mode:button.dataset.perspective}).then(function(result){toast("已创建 "+result.created+" 条"+(result.mode==="horizon"?"水平线":"透视线"))}).catch(function(error){toast(errorText(error))})}});document.getElementById("change-overlay-color").onclick=function(){host("guide.changeOverlayColor",{}).then(function(){toast("已切换构图线颜色")}).catch(function(error){toast(errorText(error))})};document.getElementById("toggle-overlays").onclick=function(){host("guide.toggleOverlays",{}).then(function(result){toast(result.visible?"构图线已显示":"构图线已隐藏")}).catch(function(error){toast(errorText(error))})}}
renderFields();renderPatterns();bind();hasValue();refreshContext();
window.addEventListener("focus",refreshContext);document.addEventListener("visibilitychange",function(){if(!document.hidden)refreshContext()});
}());
